import { createElement } from 'lwc';
import Lwc_3108_eventfrom from 'c/lwc_3108_eventfrom';

describe('c-lwc-3108-eventfrom', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-3108-eventfrom', {
            is: Lwc_3108_eventfrom
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});